/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icuxika_jni_NativeFXWindow */

#ifndef _Included_com_icuxika_jni_NativeFXWindow
#define _Included_com_icuxika_jni_NativeFXWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    getHWnd
 * Signature: (Ljavafx/stage/Stage;)J
 */
JNIEXPORT jlong JNICALL Java_com_icuxika_jni_NativeFXWindow_getHWnd(JNIEnv *,
                                                                    jclass,
                                                                    jobject);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    getWindowName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_icuxika_jni_NativeFXWindow_getWindowName(JNIEnv *, jclass, jlong);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    getClassName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_icuxika_jni_NativeFXWindow_getClassName(JNIEnv *, jclass, jlong);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    registerHotKey
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icuxika_jni_NativeFXWindow_registerHotKey(
    JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    unregisterHotKey
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icuxika_jni_NativeFXWindow_unregisterHotKey(
    JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    setWindowTransparency
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_icuxika_jni_NativeFXWindow_setWindowTransparency(JNIEnv *, jclass,
                                                          jlong);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    unsetWindowTransparency
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_icuxika_jni_NativeFXWindow_unsetWindowTransparency(JNIEnv *, jclass,
                                                            jlong);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_icuxika_jni_NativeFXWindow_initialize(JNIEnv *,
                                                                      jobject,
                                                                      jlong);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    isApplicationRunning
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_icuxika_jni_NativeFXWindow_isApplicationRunning(JNIEnv *, jclass,
                                                         jstring);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    callPrevInstance
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_icuxika_jni_NativeFXWindow_callPrevInstance(
    JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
