/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icuxika_jni_NativeFXWindow */

#ifndef _Included_com_icuxika_jni_NativeFXWindow
#define _Included_com_icuxika_jni_NativeFXWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    getHWnd
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_icuxika_jni_NativeFXWindow_getHWnd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    getWindowText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_icuxika_jni_NativeFXWindow_getWindowText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_icuxika_jni_NativeFXWindow
 * Method:    getClassName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_icuxika_jni_NativeFXWindow_getClassName
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
