<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.icuxika</groupId>
    <artifactId>JavaFX-Package-Sample</artifactId>
    <version>1.0.4</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <javafx.version>25</javafx.version>
        <moduleName>sample</moduleName>
        <mainClass>com.icuxika.Launcher</mainClass>

        <application.icon>${project.basedir}/src/main/resources/application.ico</application.icon>
        <application.package.stdout.encoding>-J-Dsun.stdout.encoding=UTF-8</application.package.stdout.encoding>
        <application.package.stderr.encoding>-J-Dsun.stderr.encoding=UTF-8</application.package.stderr.encoding>
    </properties>

    <repositories>
        <repository>
            <id>tm4e-snapshots</id>
            <name>tm4e-snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/tm4e-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-media</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>jfx-incubator-richtext</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-javafx</artifactId>
            <version>12.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-fontawesome5-pack</artifactId>
            <version>12.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-fluentui-pack</artifactId>
            <version>12.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.palexdev</groupId>
            <artifactId>materialfx</artifactId>
            <version>11.17.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.12</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.3</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.13.2</version>
        </dependency>
        <dependency>
            <groupId>org.jruby.joni</groupId>
            <artifactId>joni</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse</groupId>
            <artifactId>org.eclipse.tm4e.core</artifactId>
            <version>0.16.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.lsp4j</groupId>
            <artifactId>org.eclipse.lsp4j</artifactId>
            <version>0.24.0</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>win</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.3.0</version>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>${mainClass}</mainClass>
                                    <addClasspath>true</addClasspath>
                                    <useUniqueVersions>false</useUniqueVersions>
                                </manifest>
                            </archive>
                            <excludes>
                                <exclude>module-info.class</exclude>
                            </excludes>
                            <outputDirectory>${project.build.directory}/jars</outputDirectory>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <id>image</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>jpackage</executable>
                                    <workingDirectory>${project.basedir}</workingDirectory>
                                    <arguments>
                                        <argument>${application.package.stdout.encoding}</argument>
                                        <argument>${application.package.stderr.encoding}</argument>
                                        <argument>-n</argument>
                                        <argument>JavaFXSample</argument>
                                        <argument>-t</argument>
                                        <argument>app-image</argument>
                                        <argument>-i</argument>
                                        <argument>
                                            ${project.build.directory}/jars
                                        </argument>
                                        <argument>--main-jar</argument>
                                        <argument>${project.artifactId}-${project.version}.jar</argument>
                                        <argument>--dest</argument>
                                        <argument>${project.build.directory}/buildImage</argument>
                                        <argument>--icon</argument>
                                        <argument>${application.icon}</argument>
                                        <argument>--app-version</argument>
                                        <argument>${project.version}</argument>
                                        <argument>--java-options</argument>
                                        <argument>-XX:+PrintCommandLineFlags</argument>
                                        <argument>--java-options</argument>
                                        <argument>-XX:+UseZGC</argument>
                                        <argument>--java-options</argument>
                                        <argument>-Dprism.allowhidpi=true</argument>
                                        <argument>--java-options</argument>
                                        <argument>--enable-native-access=ALL-UNNAMED</argument>
                                        <argument>--add-launcher</argument>
                                        <argument>AppUpdateTool=launcher/AppUpdateTool.properties</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>moditect</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.3.0</version>
                        <configuration>
                            <outputDirectory>${project.build.directory}/jars</outputDirectory>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.moditect</groupId>
                        <artifactId>moditect-maven-plugin</artifactId>
                        <version>1.0.0.Final</version>
                        <executions>
                            <execution>
                                <id>add-module-infos</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>add-module-info</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/modules</outputDirectory>
                                    <modules>
                                        <module>
                                            <artifact>
                                                <groupId>org.eclipse</groupId>
                                                <artifactId>org.eclipse.tm4e.core</artifactId>
                                                <version>0.16.0-SNAPSHOT</version>
                                            </artifact>
                                            <moduleInfo>
                                                <name>org.eclipse.tm4e.core</name>
                                                <exports>
                                                    *;
                                                </exports>
                                                <requires>
                                                    *;
                                                </requires>
                                            </moduleInfo>
                                        </module>
                                        <module>
                                            <artifact>
                                                <groupId>org.eclipse.lsp4j</groupId>
                                                <artifactId>org.eclipse.lsp4j</artifactId>
                                                <version>0.24.0</version>
                                            </artifact>
                                            <moduleInfo>
                                                <name>org.eclipse.lsp4j</name>
                                                <exports>
                                                    *;
                                                </exports>
                                                <requires>
                                                    *;
                                                </requires>
                                            </moduleInfo>
                                        </module>
                                        <module>
                                            <artifact>
                                                <groupId>org.eclipse.lsp4j</groupId>
                                                <artifactId>org.eclipse.lsp4j.jsonrpc</artifactId>
                                                <version>0.24.0</version>
                                            </artifact>
                                            <moduleInfo>
                                                <name>org.eclipse.lsp4j.jsonrpc</name>
                                                <exports>
                                                    *;
                                                </exports>
                                                <requires>
                                                    *;
                                                </requires>
                                            </moduleInfo>
                                        </module>
                                    </modules>
                                    <jdepsExtraArgs>
                                        <arg>--ignore-missing-deps</arg>
                                        <arg>--multi-release</arg>
                                        <arg>9</arg>
                                    </jdepsExtraArgs>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>modular</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.3.0</version>
                        <configuration>
                            <outputDirectory>${project.build.directory}/jars</outputDirectory>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.moditect</groupId>
                        <artifactId>moditect-maven-plugin</artifactId>
                        <version>1.0.0.Final</version>
                        <executions>
                            <execution>
                                <id>add-module-infos</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>add-module-info</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/modules</outputDirectory>
                                    <modules>
                                        <module>
                                            <artifact>
                                                <groupId>org.eclipse</groupId>
                                                <artifactId>org.eclipse.tm4e.core</artifactId>
                                                <version>0.16.0-SNAPSHOT</version>
                                            </artifact>
                                            <moduleInfoSource>
                                                module org.eclipse.tm4e.core {
                                                requires org.jruby.joni;
                                                requires com.google.gson;
                                                requires org.snakeyaml.engine.v2;
                                                requires java.xml;
                                                requires jdk.xml.dom;
                                                exports org.eclipse.tm4e.core;
                                                exports org.eclipse.tm4e.core.grammar;
                                                exports org.eclipse.tm4e.core.internal.grammar;
                                                exports org.eclipse.tm4e.core.internal.grammar.dependencies;
                                                exports org.eclipse.tm4e.core.internal.grammar.raw;
                                                exports org.eclipse.tm4e.core.internal.grammar.tokenattrs;
                                                exports org.eclipse.tm4e.core.internal.matcher;
                                                exports org.eclipse.tm4e.core.internal.oniguruma;
                                                exports org.eclipse.tm4e.core.internal.parser;
                                                exports org.eclipse.tm4e.core.internal.registry;
                                                exports org.eclipse.tm4e.core.internal.rule;
                                                exports org.eclipse.tm4e.core.internal.theme;
                                                exports org.eclipse.tm4e.core.internal.theme.css;
                                                exports org.eclipse.tm4e.core.internal.theme.css.sac;
                                                exports org.eclipse.tm4e.core.internal.theme.css.util;
                                                exports org.eclipse.tm4e.core.internal.theme.raw;
                                                exports org.eclipse.tm4e.core.internal.utils;
                                                exports org.eclipse.tm4e.core.model;
                                                exports org.eclipse.tm4e.core.registry;
                                                exports org.eclipse.tm4e.core.theme;
                                                exports org.eclipse.tm4e.core.theme.css;
                                                }
                                            </moduleInfoSource>
                                        </module>
                                        <module>
                                            <artifact>
                                                <groupId>org.eclipse.lsp4j</groupId>
                                                <artifactId>org.eclipse.lsp4j</artifactId>
                                                <version>0.24.0</version>
                                            </artifact>
                                            <moduleInfoSource>
                                                module org.eclipse.lsp4j {
                                                requires transitive com.google.gson;
                                                requires transitive org.eclipse.lsp4j.jsonrpc;

                                                exports org.eclipse.lsp4j;
                                                exports org.eclipse.lsp4j.adapters;
                                                exports org.eclipse.lsp4j.launch;
                                                exports org.eclipse.lsp4j.services;
                                                exports org.eclipse.lsp4j.util;

                                                opens org.eclipse.lsp4j to com.google.gson, org.eclipse.lsp4j.jsonrpc;
                                                }
                                            </moduleInfoSource>
                                        </module>
                                        <module>
                                            <artifact>
                                                <groupId>org.eclipse.lsp4j</groupId>
                                                <artifactId>org.eclipse.lsp4j.jsonrpc</artifactId>
                                                <version>0.24.0</version>
                                            </artifact>
                                            <moduleInfoSource>
                                                module org.eclipse.lsp4j.jsonrpc {
                                                requires java.logging;

                                                requires transitive com.google.gson;

                                                exports org.eclipse.lsp4j.jsonrpc;
                                                exports org.eclipse.lsp4j.jsonrpc.json;
                                                exports org.eclipse.lsp4j.jsonrpc.json.adapters;
                                                exports org.eclipse.lsp4j.jsonrpc.messages;
                                                exports org.eclipse.lsp4j.jsonrpc.services;
                                                exports org.eclipse.lsp4j.jsonrpc.util;
                                                exports org.eclipse.lsp4j.jsonrpc.validation;

                                                }
                                            </moduleInfoSource>
                                        </module>
                                    </modules>
                                    <jdepsExtraArgs>
                                        <arg>--ignore-missing-deps</arg>
                                        <arg>--multi-release</arg>
                                        <arg>9</arg>
                                    </jdepsExtraArgs>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <id>image</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>jpackage</executable>
                                    <workingDirectory>${project.basedir}</workingDirectory>
                                    <arguments>
                                        <argument>${application.package.stdout.encoding}</argument>
                                        <argument>${application.package.stderr.encoding}</argument>
                                        <argument>-n</argument>
                                        <argument>JavaFXSample</argument>
                                        <argument>-t</argument>
                                        <argument>app-image</argument>
                                        <argument>-p</argument>
                                        <argument>
                                            ${project.build.directory}/jars${path.separator}${project.build.directory}/modules
                                        </argument>
                                        <argument>--add-modules</argument>
                                        <argument>
                                            MaterialFX,com.google.gson,java.base,jfx.incubator.richtext,org.eclipse.tm4e.core,org.kordamp.ikonli.fluentui,org.kordamp.ikonli.javafx,org.slf4j
                                        </argument>
                                        <argument>--add-modules</argument>
                                        <argument>org.jruby.joni</argument>
                                        <argument>-m</argument>
                                        <argument>${moduleName}/${mainClass}</argument>
                                        <argument>--dest</argument>
                                        <argument>${project.build.directory}/buildImage</argument>
                                        <argument>--icon</argument>
                                        <argument>${application.icon}</argument>
                                        <argument>--app-version</argument>
                                        <argument>${project.version}</argument>
                                        <argument>--java-options</argument>
                                        <argument>-XX:+PrintCommandLineFlags</argument>
                                        <argument>--java-options</argument>
                                        <argument>-XX:+UseZGC</argument>
                                        <argument>--java-options</argument>
                                        <argument>-Dprism.allowhidpi=true</argument>
                                        <argument>--java-options</argument>
                                        <argument>--enable-native-access=${moduleName}</argument>
                                        <argument>--add-launcher</argument>
                                        <argument>AppUpdateTool=launcher/AppUpdateTool-Modular.properties</argument>
                                        <argument>--jlink-options</argument>
                                        <argument>--compress zip-9</argument>
                                        <argument>--jlink-options</argument>
                                        <argument>--no-header-files</argument>
                                        <argument>--jlink-options</argument>
                                        <argument>--no-man-pages</argument>
                                        <argument>--jlink-options</argument>
                                        <argument>--strip-debug</argument>
                                        <argument>--jlink-options</argument>
                                        <argument>--ignore-signing-information</argument>
                                        <argument>--verbose</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.9.0</version>
                        <executions>
                            <execution>
                                <id>copy-dependencies</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy-dependencies</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/jars</outputDirectory>
                                    <overWriteReleases>false</overWriteReleases>
                                    <overWriteSnapshots>false</overWriteSnapshots>
                                    <overWriteIfNewer>true</overWriteIfNewer>
                                    <excludeArtifactIds>
                                        org.eclipse.tm4e.core,org.eclipse.lsp4j,org.eclipse.lsp4j.jsonrpc
                                    </excludeArtifactIds>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jni</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.14.1</version>
                        <configuration>
                            <release>${maven.compiler.release}</release>
                            <compilerArgs>
                                <arg>-h</arg>
                                <arg>${project.basedir}/src/native/include</arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.9.0</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/jars</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-and-filter-allatori-config</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/target</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/allatori</directory>
                                    <includes>
                                        <include>allatori.xml</include>
                                    </includes>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>run-allatori</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>java</executable>
                    <arguments>
                        <argument>-Xms128m</argument>
                        <argument>-Xmx512m</argument>
                        <argument>-jar</argument>
                        <argument>${basedir}/allatori/allatori.jar</argument>
                        <argument>${basedir}/target/allatori.xml</argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>