# We only want minification, not obfuscation.
-verbose

-keepattributes Exceptions,InnerClasses,Signature,Deprecated,
                SourceFile,LineNumberTable,*Annotation*,EnclosingMethod

-renamesourcefileattribute SourceFile

# Entry point to the app.
-keep class com.icuxika.Launcher { *; }
-keep class com.icuxika.AppUpdateTool { *; }
-keep class com.icuxika.jni.NativeFXWindow { *; }

-keep class com.icuxika.controller.** { *; }
-keep class com.icuxika.model.** { *; }
