# We only want minification, not obfuscation.
-verbose

# Entry point to the app.
-keep class com.icuxika.Launcher { *; }
-keep class com.icuxika.AppUpdateTool { *; }
-keep class com.icuxika.jni.NativeFXWindow { *; }

-keep class com.icuxika.model.** { *; }
