// Generated by jextract

package com.icuxika.jextract.win32;

/**
 * {@snippet lang = c:
 * typedef struct tagKBDLLHOOKSTRUCT {
 *     DWORD vkCode;
 *     DWORD scanCode;
 *     DWORD flags;
 *     DWORD time;
 *     ULONG_PTR dwExtraInfo;
 * } KBDLLHOOKSTRUCT
 *}
 */
public class KBDLLHOOKSTRUCT extends tagKBDLLHOOKSTRUCT {

    KBDLLHOOKSTRUCT() {
        // Should not be called directly
    }
}

