// Generated by jextract

package com.icuxika.jextract.win32;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct tagKBDLLHOOKSTRUCT {
 *     DWORD vkCode;
 *     DWORD scanCode;
 *     DWORD flags;
 *     DWORD time;
 *     ULONG_PTR dwExtraInfo;
 * } KBDLLHOOKSTRUCT
 * }
 */
public class KBDLLHOOKSTRUCT extends tagKBDLLHOOKSTRUCT {

    KBDLLHOOKSTRUCT() {
        // Should not be called directly
    }
}

