name: Build installer for Windows
on:
  push:
    branches:
      - java17

jobs:
  build-app:
    strategy:
      matrix:
        os: [ windows-2019 ]
    name: Build the application
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - run: $Env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"

      - name: build
        run: .\gradlew.bat jpackage
        shell: pwsh

      - name: copy
        run: New-Item -Name "staging" -ItemType "directory"; Copy-Item ".\build\build-package\*.msi" -Destination "staging"
        shell: pwsh

      - name: get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: upload build result
        uses: actions/upload-artifact@v2
        with:
          name: JavaFXSample-${{ steps.current-time.outputs.formattedTime }}-${{ matrix.os }}
          path: staging